### ISSUE TITLE
Arm64/v8 Images

### ISSUE THREAD

**Issue by samkhawase** [alvr/alpine-android#10]
Hi,

Thanks a lot for creating the slim alpine images for Docker. Would it be possible for you to add support for **Arm64/v8** arch? I've an Apple Silicon M1 macbook and other images don't work on it.

I tried forking this repo, but didn't go far as there are a lot of changes required with credentials etc.

We could leverage the `platforms` argument of the Docker buildx action? 
```
 - name: Build Android Base JDK${{ matrix.jdk }}
   uses: docker/build-push-action@v2
   with:
     context: ./docker
     file: ./docker/base.Dockerfile
     push: true
     tags: ${{ steps.docker_meta.outputs.tags }}
     build-args: |
       JDK_VERSION=${{ matrix.jdk }}
     # Limit to platforms supported by base image
     platforms: |
       linux/arm64/v8

```
Here is a PR the has the relevant build .yml file that builds for arm64/v8 arch: 
https://github.com/docker/setup-buildx-action/issues/54
